FORMAT: 1A
HOST: http://yourITASserver:4715/

# ITAS IServices

## AccessToken [/AT]
Model Header containing AccessToken

+ Model
    + Header

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

# Group ITAS Services Control
Endpoints to get and set the status of ITAS windows services

# Group Key Value Pair Store

The Key Value Pair Store (kvpstore) allows users to store and retrieve arbitrary key/value pairs, organised into groups of similar keys.

## Collection of groups [/kvpstore]

### List all groups [GET]

+ Request
    [AccessToken][]

+ Response 200 (application/json)
    + Attributes (object)
        + groupsTotal: 2 (number)
        + data (array [KvpGroup List])

### Create new group [POST]

+ Request
    + Body

            {
                "groupName": "groupC",
                "groupDescription": "description for new group"
            }

    + Header

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg


+ Response 201 (application/json)
    + Attributes (KvpGroup)
        + keysTotal: 0 (number)


## Single group [/kvpstore/{groupName}]

+ Parameters
    + groupName (required, string, `groupA`) - ID of the group

### Get details of a group and list all its key/value pairs [GET]

+ Request
    [AccessToken][]

+ response 200 (application/json)
    + Attributes (KvpGroup)
        + keysTotal: 2 (number)
        + data (array [KvpKey])

### Create new key/value pair [POST]

+ Request
    + Body

            {
                "keyName": "key",
                "keyValue": "new sample string",
            }

    + Header

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg


+ response 201 (application/json)
    + Attributes (KvpKey)


### Delete a specific group [DELETE]

+ Request
    [AccessToken][]

+ Response 200 (application/json)
    + Attributes (KvpGroup)
        + response: deleted (string)
        + keysAffected: 2 (number)



## Single Key [/kvpstore/{groupName}/{keyName}]
+ Parameters
    + groupName (required, string, `groupA`) - ID of the group
    + keyName (required, string, `nameA`) ... Name of the key in a key/value pair


### Get a single key/value pair [GET]

+ Request
    [AccessToken][]

+ response 200 (application/json)
    + Attributes (KvpKey)


### Delete a specific key [DELETE]

+ Request
    [AccessToken][]

+ response 200 (application/json)
    + Attributes (KvpKey)
        + response: deleted (string)




# Group Data Functions

## Frozen DB Check [/datafunctions/frozen/dbcheck]
### Check [GET]
+ Request
    [AccessToken][]

+ Response 200 (application/json)



# Group Physical Contract Metadata
Retrieve metadata and other information about ITAS Physical Contracts

## Query facets [/metadata/contract/physical/{TradingEntityId}/]
Retrieve distinct values for each property within a set of contracts.

### Get metadata [GET]

|property|description|type|max length|notes|constraint|
|--------|-----------|----|----------|-----|----------|
|Department||array of `object`||see `Department List` definition||
|Counterparty||array of `object`||see `ClientAccount List` definition||
|Trader||array of `object`||see `UserAccount` definition||
|Commodity||array of `object`||see `Commodity` definition||
|Terminal||array of `object`||see `Terminal` definition||
|ContractType|phys01_contype|`string`|1|||
|ThirdParty||`boolean`||||
|StockOwner||`object`||Stock Owner delivered as an `AccountHeader` object||
|ContractDate|phys01_condate|`number`||||


+ Request (application/json)
    + Header

            AccessToken:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

    + body

            {
                "Department": ["9900", "5100", "GBPT"],
                "Counterparty": ["AFRICA.P"],
                "Trader": ["JB"],
                "Commodity": ["ORG", "WHT"],
                "Terminal": [],
                "ContractType": ["S"],
                "Third Party": ["N"],
                "StockOwner": [],
                "DateFrom": "2010-02-31T00:00:00Z",
                "DateTo": ""
            }

+ Parameters
    + TradingEntityId (optional, string) - identify specific trading entity

+ Response 200 (application/json)
    + Attributes (object)
        + Department (array [Department List])
        + Counterparty (array [ClientAccount List])
        + Trader (array [UserAccount])
        + Commodity (array [Commodity])
        + Terminal (array [Terminal])
        + ContractType (array [string])
        + Third Party (array [])
        + StockOwner (array [AccountHeader])
        + ContractDate (object)
            + Max: `1980-02-31T00:00:00Z` (string)
            + Min: `2012-08-01T00:00:00Z` (string)


# Group Codes
Web services to support creating, reading and updating ITAS Codes

+ Response 200 (application/json)

# Group Data Object Definitions
List of re-usable Data Objects referenced as `object` types. Note that these endpoints are not accessable and only here for reference purposes.

# Data Structures

## 200 SuccessResponse (object)
+ Value: Success (string)

## 200 CreateResponse (object)
+ Value: Created (string)

## 200 AuthoriseResponse (object)
+ Value: Authorised (string)

## 201 UpdateResponse (object)
+ Value: Updated (string)


## 400 Response (object)
+ Response
    + Value: 400 Bad Request (string)
+ Messages (array [400 ErrorMessageDetail])

## 400 BadPropertyResponse (object)
+ Response
    + Value: 400 Bad Request (string)
+ Messages (array[400 BadPropertyErrorMessageDetail])

## 400 ErrorMessageDetail (object)
+ Severity: Error (string)
+ Message: `API5058 - Data : The mandatory field {fieldName} was missing in the request body.` (string)

## 400 WarningMessageDetail (object)
+ Severity: Warning (string)
+ Message: `API50xx - Data : The field {fieldName} was not found.` (string)

## 400 InfoMessageDetail (object)
+ Severity: Information (string)
+ Message: `API50xx - Data : Now create xyz.` (string)

## 400 BadPropertyErrorMessageDetail (object)
+ Severity: Error (string)
+ Message: `API5068 - API : The value sent in the querystring variable {Property} is not allowed.` (string)

## 404 Response (object)
+ Response
    + Value: 404 Objet not found (string)
+ Messages (array[404 ErrorMessageDetailMessage])

## 404 ErrorMessageDetailMessage (object)
+ Severity: Warning (string)
+ Message: `API5067 - API : The value {TradingEntityId} sent as the TradingEntitiyId does not exist.` (string)

## accessToken (object)
+ Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg (string)

## AccountHeader (object)
+ AccountType: C (string)
+ AccountId: 00040444.P (string)
+ AccountDescription: Nigeria Trading Dept (string)
+ EDICode: ABC1234 (string)
+ Status: F (string)

## ClientAccount List (object)
+ ClientAccountId: ABCDEF.P (string)
+ Title: `ACME Trading Company` (string)
+ ClientTypeCode: H (string)
+ Status: O (string)
+ PrivilegeLevel: 9 (number)
+ CanBeBuyer: true (boolean)
+ CanBeSeller: true (boolean)
+ CanBeAgent: true (boolean)
+ CanBeShipper: true (boolean)
+ CanBeDerivativeClient: true (boolean)
+ CanBeDerivativeBroker: true (boolean)
+ EDICode: extABCDEF (string)


## Commodity (object)
+ CommodityCodePart1: ORG (string)
+ CommodityCodePart2: `S1-45` (string)
+ CommodityCodePart3: FAIRT (string)
+ CommodityCodePart4: qwe (string)
+ CommodityCodePart5: ty (string)
+ CommodityDescription: Organic Golden Fairtrade Sugar (string)
+ DocumentText: Org Golden S1 45 ICUMSA (string)
+ CountryCode: MAL (string)
+ EDICode: ABC1234 (string)
+ Status: F (string)

## Department List (object)
+ DepartmentId: 5100 (string)
+ DepartmentDescription: African Trading (string)
+ NominalCategoryId: AF (string)
+ CountryId: GB (string)
+ EDICode: 1234 (string)
+ Status: F (string)

## KvpKey (object)
+ keyName: nameA (string)
+ keyValue: sample string (string)
+ keyUrl: kvpstore/groupA/nameA
+ groupName: groupA (string)
+ groupDescription: sample string value  (string)
+ groupID: 1 (number)
+ groupUrl: kvpstore/groupA (string)

## KvpKey List (object)
+ keyName: nameA (string)
+ keyValue: sample string (string)
+ keyUrl: kvpstore/groupA/nameA

## KvpGroup (object)
+ groupName: groupC (string)
+ groupID: 3 (number)
+ groupDescription: description for new group (string)
+ groupUrl: /kvpstore/groupC (string)

## KvpGroup List (object)
+ groupName: groupC (string)
+ groupID: 3 (number)
+ groupUrl: /kvpstore/groupC (string)

## Pagination (object)
+ Total: 547 (number) - total number of records available
+ Top: 200 (number) - max number returned per message
+ Skip: 400 (number) - number of records skipped
+ Returned: 146 (number) - actual number returned

## Terminal (object)
+ TerminalId: ADEL (string)
+ TerminalDescription: `Santos-Santa Adelia` (string)
+ countryCode: BRA (string)

## UserAccount (object)
+ UserAccountId: JS (string)
+ UserAccountName: JSMITH (string)
+ UserAccountDescription: Joseph Smith (string)